name: build
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v1
      - name: 'Set up JDK 23'
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23-ea'
      - name: Build
        run: mvn --no-transfer-progress verify && cp target/holy-agent.jar holy-agent.jar
      - name: Release
        uses: ncipollo/release-action@v1
        with:
            artifacts: "holy-agent.jar"
            replacesArtifacts: true
            tag: latest
            token: ${{ secrets.GITHUB_TOKEN }}
            allowUpdates: true          
          
