name: Generate Holyrics runtime
on:
  workflow_dispatch:
    inputs:
      runtime_version:
        description: 'JDK version'
        default: '20'
        required: true
      
jobs:
  build-windows:
    runs-on: 'windows-latest'
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v1
      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: ${{ github.event.inputs.runtime_version }}
          distribution: 'graalvm'        
      - name: Generate runtime
        run: |
          mvn package
      - name: Release
        uses: ncipollo/release-action@v1
        with:
            artifacts: "holytime-windows.zip"
            replacesArtifacts: false
            tag: Holytime-JDK-${{ github.event.inputs.runtime_version }}
            token: ${{ secrets.GITHUB_TOKEN }}
            allowUpdates: true
          
  build-linux:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v1
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: ${{ github.event.inputs.runtime_version }}
          distribution: 'graalvm'
      - name: Generate runtime
        run: |
          mvn package
      - name: Release
        uses: ncipollo/release-action@v1
        with:
            artifacts: "holytime-linux.zip"
            replacesArtifacts: false
            tag: Holytime-JDK-${{ github.event.inputs.runtime_version }}
            token: ${{ secrets.GITHUB_TOKEN }}
            allowUpdates: true
