name: Generate Holyrics runtime
on:
  workflow_dispatch:
    inputs:
      runtime_version:
        description: 'JDK version'
        default: 'GA'
        required: true
      
jobs:
  build-windows:
    runs-on: 'windows-latest'
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v1
      - name: 'Set up JDK ${{ github.event.inputs.runtime_version }}'
        uses: oracle-actions/setup-java@v1
        with:
          website: jdk.java.net
          release: ${{ github.event.inputs.runtime_version }} 
      - name: Generate runtime
        run: |
          ./generate-runtime-windows.ps1
      - name: Release
        uses: ncipollo/release-action@v1
        with:
            artifacts: "holytime-windows.zip"
            replacesArtifacts: false
            tag: Holytime-JDK-${{ github.event.inputs.runtime_version }}
            token: ${{ secrets.GITHUB_TOKEN }}
            allowUpdates: true
          
  build-linux:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v1
      - name: 'Set up JDK ${{ github.event.inputs.runtime_version }}'
        uses: oracle-actions/setup-java@v1
        with:
          website: jdk.java.net
          release: ${{ github.event.inputs.runtime_version }} 
      - name: Generate runtime
        run: |
          bash ./generate-runtime-linux.sh
      - name: Release
        uses: ncipollo/release-action@v1
        with:
            artifacts: "holytime-linux.tar.gz"
            replacesArtifacts: false
            tag: Holytime-JDK-${{ github.event.inputs.runtime_version }}
            token: ${{ secrets.GITHUB_TOKEN }}
            allowUpdates: true
